name: eppo_web_sdk
description: Eppo SDK for Flutter Web
version: 1.0.0-alpha.3
repository: https://github.com/Eppo-exp/dart-web-sdk
license: MIT

environment:
  # Dart 3.3.0 is the first version to support js interop
  sdk: ^3.3.0

# This package only works on the web platform
platforms:
  web:

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
